title: Florian Fahrenbach
description: Personal website – Enterprise Architecture | Data Governance | Process Management
logo: /assets/img/FlorianFahrenbach.jpg
show_downloads: false  # Cayman doesn’t usually use this, so you can disable
google_analytics:      # keep empty or add your GA ID if you want tracking

# Change the theme to Cayman
theme: jekyll-theme-minimal